title: Pretty in Font
description: A blog about the most iconic romcoms and their titles' font
header_text: ""
footer_text: Copyright 2020 Martina Currenti
header_feature_image: ../uploads/the-fonts-that-made-you-fall-in-love-3-.png
bannerheight: 10vmax
logo: ../uploads/screenshot-2020-09-25-at-12.38.29.png
favicon: ../uploads/progetto-senza-titolo-1-.png
gridlayout: false
fixednavbar: true
upzoom: true
items: []
