title: Pretty in Font
description: A blog about the most iconic romcoms and their titles' font
header_text: ""
footer_text: Copyright 2020 Martina Currenti
header_feature_image: ../uploads/pretty-in.png
bannerheight: 10vmax
logo: ../uploads/2.png
favicon: ../uploads/3.png
gridlayout: false
fixednavbar: false
upzoom: false
items: []
